### ISSUE TITLE
Text is clipped by the ListItem

### ISSUE THREAD

**Issue by Bikeman868** [psychobolt/react-pie-menu#10]
The `<li>` element has its CSS set to `overflow:hidden` and the `<div>` element within it (I think this is `contentContainer`) is wider than the pie slice, so the content inside of it is clipped.

I tried setting `overflow:visible` in the `container` css as follows, but this doesn't help. Ideally the `contentContainer` `<div>` should be sized to the pie slice to avoid this issue.

```javascript
  const theme = {
    pieMenu: {
      container: css`
        border: 1px solid lightgrey;
        background-color: rgba(255, 255, 255, 0.85);
      `,
    },
    slice: {
      container: css`
        cursor: pointer;
        overflow: visible;
        background: rgba(0, 0, 0, 0.02);
        &[kind='action'] {
          background: rgba(128, 255, 128, 0.1);
        }
        &[kind='nav'] {
          background: rgba(128, 128, 255, 0.05);
        }
        &:hover,
        &[active='true'],
        &[_highlight='true'] {
          background: rgba(255, 255, 255, 0.85);
        }
      `,
    },
  };
```
![Screen Shot 2021-01-22 at 3 56 02 PM](https://user-images.githubusercontent.com/5679259/105561015-791c9e80-5cca-11eb-81ee-7f58bc59a1e3.png)

**Comment by psychobolt** [comment]
The contentContainer's purpose is to help center the content for the Slice. Unfortunately, it doesn't help calculate layout space. If you want specific clipping or text wrapping, you will have to set your own in the slice's content manually: e.g. 
```jsx
const theme = {
  slice: {
    content: css`
      width: 150px; /* estimated width */
      /* wrap or clamp text styles... */
    `,
  }
};
```

**Comment by Bikeman868** [comment]
This is kind of tricky because the horizontal space available is different for every slice. As the number of slices increases, the horizontal space available for the top and bottom slices becomes almost unusable.

In my case the text on the Pie slices is data from the database, so I can't hand optimize each slice, I need to calculate the values somehow.

For icons and short static phrases, I think your current solution looks great. For my application I think that ideally I should have two groups of slices, one on the left side and one on the right side with no slices that are near vertical. I think I can do this by adding dummy slices that are made invisible via CSS, but they would still be clickable.

Can you think of any features that could be added to make my use case work a little better?

**Comment by psychobolt** [comment]
The overflow css can already be controlled by overriding the style in the theme object:
```js
const theme = {
  pieMenu: {
    item: css`
      overflow: visible;
    `,
    },
  },
};
```
But the clipping also affects the slice's background. Calculating the vertical and horizontal dimensions of the content will be difficult, but possible. What needs determine is an optimal `radius` size, based on some criteria e.g. max-width or max-height of `content`. This will need to be calculated on post-render.

**Comment by Bikeman868** [comment]
I didn't realize that I can have `item` in my theme. This will already improve the situation.
Thank you for all of your suggestions.
