### ISSUE TITLE
onSelect of Slice component registers the event twice

### ISSUE THREAD

**Issue by RvsB** [psychobolt/react-pie-menu#101]
when we click on the slice, the callback provided gets called twice.

**Comment by RvsB** [comment]
@psychobolt please help!

**Comment by psychobolt** [comment]
The Storybook example shows onSelect called once in the interaction console: https://psychobolt.github.io/react-pie-menu/?path=/story/examples--context-menu . Please provide code snippet and example of your use case.

**Comment by RvsB** [comment]
https://codesandbox.io/s/pie-menu-testing-duhuzz?file=/App.tsx 

the above provided link is for a code sandbox, implementing the pie-menu with antv graphin  library, when you click on any of the slices, you can see the respective message being logged into the console twice, I check the code of the slice component, but everything seemed fine, don't know why this behaviour is happening @psychobolt

**Comment by psychobolt** [comment]
Thanks for providing the sandbox. I will reach out once I figure out the main problem.

**Comment by RvsB** [comment]
> Thanks for providing the sandbox. I will reach out once I figure out the main problem. Meanwhile, you can try to wrap the callbacks in a debounce for a quick workaround.

Yes, sounds like a good workaround.

**Comment by RvsB** [comment]
One more thing i noticed with the pie menu component is, if you zoom on the graph enough and open the pie menu, you wont be getting any hover highlighting on some of the slices, any idea why its caused? @psychobolt

**Comment by psychobolt** [comment]
> One more thing i noticed with the pie menu component is, if you zoom on the graph enough and open the pie menu, you wont be getting any hover highlighting on some of the slices, any idea why its caused? @psychobolt

For most of my testing with the example you provided. Zooming in and out with mousewheel seems to be fine on Chrome Desktop. What client are you using?

**Comment by psychobolt** [comment]
@RvsB I created a patch with the debounce workaround I suggested. You can continue using your fix, but it's included in [1.0.0-alpha.4](https://www.npmjs.com/package/react-pie-menu/v/1.0.0-alpha.4) if wish to upgrade. If you have any other issues unrelated to this fix, please open another ticket.
