### ISSUE TITLE
How to add delay on click?

### ISSUE THREAD

**Issue by AscaL** [psychobolt/react-pie-menu#13]
Hi, thanks for the awesome project!
I was wondering if it's possible to add a delay so that if i mouse press for (for example) more than 0.5 seconds the pie menu pops out, otherwise it does not.
My idea was to add the pie-menu to only a specific part of the UI, that already interacts with mouse presses.

Thanks in advance :)

**Comment by psychobolt** [comment]
You can take a look at the Context Menu [example](https://psychobolt.github.io/react-pie-menu/?path=/story/examples--context-menu) for an example on triggering mouse. See [source](https://github.com/psychobolt/react-pie-menu/tree/master/stories/Examples/ContextMenu). I don't think its too difficult to add a `setTimeout`.

**Comment by AscaL** [comment]
Thanks a lot, I've managed to do it with your help :)
