### ISSUE TITLE
onMouseOver causes child elements to also trigger the callback

### ISSUE THREAD

**Issue by andrewshannon12** [psychobolt/react-pie-menu#14]
onMouseOver causes child elements to trigger it's callback which results in functions being run multiple times even if the mouse hasn't left the element. I think adding onMouseEnter would add flexibility since it will only run once "on mouse enter" since it does not react to event bubbling.

**Comment by psychobolt** [comment]
Enchancement is included in 0.3.1. See [README](https://github.com/psychobolt/react-pie-menu#onmouseenter-e-syntheticmouseeventt--void).
