### ISSUE TITLE
onMouseOver is triggered while outside of the viewable item element

### ISSUE THREAD

**Issue by andrewshannon12** [psychobolt/react-pie-menu#15]
To deomonstrate, the red dot represents my cursor:
![mouseOverExample](https://user-images.githubusercontent.com/86409819/126606050-2127b9f4-00e7-4e8c-9bd0-c52807a5f7c2.png)

Since it only works on the corners, I have narrowed it down to either the parent UI or Div:

On inspection, the parent UI and Parent Div:
![parentDiv](https://user-images.githubusercontent.com/86409819/126606046-c37e3803-bbfa-46d0-ab27-1d29ed7e58ee.png)

And also possibly an issue with the overflow of the item element:
![item](https://user-images.githubusercontent.com/86409819/126606054-9fd93b85-a76a-400c-9186-1e73084a3ea5.png)

**Comment by psychobolt** [comment]
Fix is included in [0.3.1](https://www.npmjs.com/package/react-pie-menu/v/0.3.1).
