### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by DeBaum** [psychobolt/react-pie-menu#2]
Based on your readme you already know TypeScript. So it should be easy for you to provide a definition file.

**Comment by psychobolt** [comment]
You must mean the flow type annotations on the readme. I have no plans to add TypeScript support, but it would be nice to have.

**Comment by keyserj** [comment]
FYI I created a PR for this in DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63065
