### ISSUE TITLE
Slice collision regions don't scroll with page properly

### ISSUE THREAD

**Issue by NyarukoDev** [psychobolt/react-pie-menu#22]
I have placed a red region over the approximate area where mouse collision occurs. The first is with no scrolling having being done yet (page positioning on load) which shows the expected behaviour:
![image](https://user-images.githubusercontent.com/23709404/130599245-7c6d73db-58ce-4a7c-a94d-ce65c225023a.png)
If I scroll the page down, however, this region seems to scroll faster than the rest of the page (this also happens with side to side scrolling it seems):
![image](https://user-images.githubusercontent.com/23709404/130599550-b4af1731-2d5c-42c2-b006-c2ba92fbb4ae.png)

Is there anything we're missing that would interfere with the collision regions in this way?
![image](https://user-images.githubusercontent.com/23709404/130600381-112d65dc-12e7-4d19-a86c-04c17e67a362.png)

Cheers!

**Comment by psychobolt** [comment]
Can you provide some sample code to show me how you are adding the red region over the Pie Menu?

**Comment by NyarukoDev** [comment]
The red overlay isn't pro

**Comment by psychobolt** [comment]
Fix in [0.3.2](https://www.npmjs.com/package/react-pie-menu/v/0.3.2)

**Comment by NyarukoDev** [comment]
Hi, I'm still running into this issue in 0.3.2 when scrolling vertically, I'll get a clip of the problem uploaded here shortly

**Comment by NyarukoDev** [comment]
https://www.youtube.com/watch?v=TH77LQjbmY8

**Comment by psychobolt** [comment]
Ok, looks like the the offset values isn't working perfectly in most cases. I'll look into it.

**Comment by psychobolt** [comment]
@NyarukoDev Can you try [0.3.3](https://www.npmjs.com/package/react-pie-menu/v/0.3.3) and let me know if the issue still reproduces?

**Comment by NyarukoDev** [comment]
Can no longer reproduce bug, looks like that was the fix, cheers!
