### ISSUE TITLE
Pie Menu not opening on Full calander for mobile

### ISSUE THREAD

**Issue by TobiasKC** [psychobolt/react-pie-menu#34]
Hi, 

Firstly thanks for the great package.

Having trouble getting the Pin Wheel to open on top of Full Calender package (https://fullcalendar.io/) for mobile views. Works great on desktop views. Versions and Calender plug-ins below:

- "react-pie-menu": "^0.3.3",
- "@fullcalendar/core": "5.5.1",
- "@fullcalendar/daygrid": "5.5.0",
- "@fullcalendar/interaction": "5.5.0",
- "@fullcalendar/list": "5.5.0",
- "@fullcalendar/react": "5.5.0","
- @fullcalendar/timegrid": "5.5.0",

//Imports:

import FullCalendar, {
  CalendarApi,
  DateSelectArg,
  EventApi,
  EventInput,
} from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import listPlugin from "@fullcalendar/list";
import { EventClickArg } from "@fullcalendar/core";
import PieMenu, { Slice } from "react-pie-menu";
import React, { useState } from "react";

//Open Wheel Repex:
//Boolean determines if Wheel renders
```
  const [wheel, setWheel] = useState<
    [CalendarApi | null, boolean, DateSelectArg | null]
  >([null, false, null]);

  function handleDateSelect(selectInfo: DateSelectArg) {
    const calendarApi = selectInfo.view.calendar;
    setWheel([calendarApi, true, selectInfo]);
  };
```
//Calender
``` <FullCalendar
        plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin]}
        headerToolbar={{
          left: "prev,next today",
          center: "title",
          right: "dayGridMonth,listMonth",
          // right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek",
        }}
        initialView="dayGridMonth"
        editable={true}
        selectable={true}
        selectMirror={true}
        dayMaxEvents={true}
        weekNumbers={true}
        nowIndicator={true}
        select={handleDateSelect}
        firstDay={1}
      />``` 

Cheers

**Comment by psychobolt** [comment]
@TobiasKC 

It would be useful to provide the render code for PieMenu so I can see what parameters are being passed and order of other components, themes, html,, styles to be displayed, e.g. (

```js
const PieComponent = (
  <PieMenu {...props}>
    {...slices}
  </PieMenu>
);

// where it is rendered
return (
  <>
    <Calendar />
     {wheel && <PieComponent />}
  </>
);
```
)

**Comment by psychobolt** [comment]
I've integrated Pie Menu with the Full Calendar sandbox from the official docs (https://codesandbox.io/s/react-calendar-and-pie-menu-0-3-3-demo-upyi6?file=/src/DemoApp.jsx) It seems to have some styling issues in both desktop and mobile views.

@TobiasKC Can you provide a screenshot for your implementation desktop and mobile view?

**Comment by TobiasKC** [comment]
Hi Michael,

Thanks for the quick reply.

See: https://drive.google.com/drive/folders/1NAs0ULLjq8Qvd6UVADN_C11b6K2fYaTy?usp=sharing

Code sample and Images in there. Cannot get Wheel to render on Mobile so couldn't include.

If you want a minimal reprex in a blank react App let me know.

Cheers

Toby

________________________________

**Comment by psychobolt** [comment]
@TobiasKC 

setWheel is called on what events?

**Comment by TobiasKC** [comment]
Hi Michael, 

I've uploaded a minimal reprex to the same Google Drive link. Everything you need should be findable in there. 

Let me know if you need anything else

Cheers

Toby

**Comment by psychobolt** [comment]
@TobiasKC Based on my testing, the select handler `handleDateSelect` for full calendar is not firing for mobile when used as a prop.

```js
/* Below code is not fired on mobile touch when passed as a prop */
function handleDateSelect(selectInfo) {
  const calendarApi = selectInfo.view.calendar;
  setWheel([calendarApi, true, selectInfo]);
  alert('touch!');
}
```

**Comment by psychobolt** [comment]
As in comment above, issue from the Full Calendar library.
