### ISSUE TITLE
Adding Tooltip for slices

### ISSUE THREAD

**Issue by bozali** [psychobolt/react-pie-menu#4]
Hi,
is it somehow possible to add tooltips to the slices, if hovering the slice e.g.
`<Slice tooltip="Does something />`?

**Comment by psychobolt** [comment]
It seems that you would have to use it as ```attrs``` prop, e.g.

```jsx
  <Slice attrs={{ tooltip: 'Does something' }} />
```

Reference, https://github.com/psychobolt/react-pie-menu/blob/db2580ce5a1553df86ac0f1afa53e917be3aa508/src/Slice/Slice.component.js#L60

**Comment by bozali** [comment]
Thank you very much! I did not see that.
