### ISSUE TITLE
Awesome component! how to set the BorderStyle of each Slice ?

### ISSUE THREAD

**Issue by pomelo-nwu** [psychobolt/react-pie-menu#5]
I used your PieMenu component in my ContextMenu Component, which is awesome！ but there is a small problem, how to set the Border style of each Slice, For example, add a blue border to each Slice in the figure below
![image](https://user-images.githubusercontent.com/10703060/102991489-414bfb00-4554-11eb-942a-ceba826e79d7.png)

You can view the source code here：https://github.com/antvis/Graphin/blob/graphin-2.0/packages/graphin-components/src/ContextMenu/demos/PieMenu.tsx
thanks～

**Comment by psychobolt** [comment]
You can add the border style for the item element, which would style all the slices:
https://github.com/antvis/Graphin/blob/e2dea50a46422374ee6b17633fd9f83a252fb4ee/packages/graphin-components/src/ContextMenu/demos/PieMenuTheme.ts#L31
try changing the line to:
```css
border: 2px solid #3477de;
```
This will probably work for most cases...

**Comment by andrewshannon12** [comment]
You can add internal borders using a pseudo element inside of your theme like this: 

const theme = {
    pieMenu: {
      item: css`
        overflow: hidden;
        &::after {
          content: "";
          position: absolute;
          bottom: 0;
          width: 64px;
          border-bottom: 1px solid white;
        }
      `,
    },
  };
