### ISSUE TITLE
bump styled-components-theme-connector

### ISSUE THREAD

**Issue by FezVrasta** [psychobolt/react-pie-menu#59]
Hi, the latest version of styled-components doesn't seem to work with the version of `styled-components-theme-connector` used by this package. Do you think you could bump it?

**Comment by psychobolt** [comment]
Thanks, will do. For now, you can use overrides to revert to using the old package. 

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

```json
 "overrides": {
    "styled-components-theme-connector": "0.1.5"
  }
```

**Comment by FezVrasta** [comment]
The problem is with 0.1.5, if I upgrade I can build my app correctly but then I get other errors, namely:

![image](https://user-images.githubusercontent.com/5382443/161822452-622805e3-a3a4-408c-be28-53763e7ba48f.png)

**Comment by psychobolt** [comment]
Bump version in pre-release of [1.0.0](https://github.com/psychobolt/react-pie-menu/releases/tag/react-pie-menu%401.0.0-alpha.0).
