### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by Bikeman868** [psychobolt/react-pie-menu#8]
Just to test things out, I tried adding a very simple pie menu like this:
```
const PopupMenu = ({ graphNode }) => {
  return (
    graphNode && (
      <PieMenu radius="125px" centerRadius="30px" centerX={200} centerY={300}>
        <Slice>Slice 1</Slice>
        <Slice>Slice 2</Slice>
        <Slice>Slice 3</Slice>
        <Slice>Slice 4</Slice>
      </PieMenu>
    )
  );
};
```

This results in the pie menu being at the bottom of the page because the top and left are not set. See screenshot below.
<img width="407" alt="Screen Shot 2021-01-21 at 2 42 39 PM" src="https://user-images.githubusercontent.com/5679259/105421528-19a18e80-5bf7-11eb-9f8b-0c94a6ba90e9.png">

**Comment by psychobolt** [comment]
You should use CSS units. E.g. centerX="200px" centerY="300px".

**Comment by Bikeman868** [comment]
Ah, thanks. It was hard to tell from the example at the top of the readme that these were strings with units.
