### ISSUE TITLE
How to apply styling

### ISSUE THREAD

**Issue by Bikeman868** [psychobolt/react-pie-menu#9]
Hi,

Your readme file has a few pieces of information about styling, but it's very hard for me to figure out how to join these pieces together into a working example.

For example you document that the `Slice` component has a `bg` prop but don't provide any information about what it should be set to. I tried this:

```javascript
        {views &&
          views.map((view) => (
            <Slice
              key={view.id}
              bg="rgba(220, 220, 220, 0.8)"
              onSelect={() => {
                handleRelated(view);
              }}>
              <Typography variant="caption" color="textPrimary">
                {view.name}
              </Typography>
            </Slice>
          ))}
```

but the background does not change at all.

You have a piece on "coloring a slice's background" like this:
```javascript
import { background } from 'react-pie-menu';
import { css } from 'styled-components';

export const slice = css`
  ${background('#ff0000')}
  /* or interpolate from colors scale in a theme */
  ${background('red.100')}
  ${background('tomato')}
`;
```
which just exports a string constant. Unless something else is importing this constant I can't see it having any effect, and in any case I want different background colors for different kinds of slice.

Please update the readme file with an example that brings these things together into a practical working example.

Thanks.

**Comment by psychobolt** [comment]
HI, the current [README](https://github.com/psychobolt/react-pie-menu/tree/master) on the repo doesn't reflect the current release. Please refer to the [README](https://github.com/psychobolt/react-pie-menu/tree/react-pie-menu%400.2.5) with the release.

**Comment by psychobolt** [comment]
For styling your own slice with the current release (v0.2.5), you should create your own style and pass that through the theme provider. E.g.:

```jsx
import { ThemeProvider, css } from 'styled-components';

const theme = {
  slice: {
    container: css`
      background: radial-gradient(transparent ${({ centerRadius }) => `${centerRadius}, rgba(109, 109, 109, 0.925) ${centerRadius}`}); /* background */
    `;
  }
};

export default ({ pieMenu }) => (
  <ThemeProvider theme={theme}>{pieMenu}</ThemeProvider>
);
```

**Comment by Bikeman868** [comment]
That's great. Thanks for your help.
This is a great component, thank you for writing it. Linking [this page](https://github.com/psychobolt/react-pie-menu/tree/master/stories/Examples) from the README would be a big help to people trying to get off the ground.
