### ISSUE TITLE
Fails first client-side render after rendering server-side (via Next.js)

### ISSUE THREAD

**Issue by keyserj** [psychobolt/react-pie-menu#99]
Trying to [render a basic pie](https://github.com/keyserj/ameliorate/blob/pie-import-issue/web/src/pages/pie.tsx#L10-L15) via Next.js, I ran into the error
```
Warning: Prop `id` did not match. Server: "slice_nRYwgw795" Client: "slice_A6Q3M3Ww1"
```
and the pie isn't interactive.

This isn't a big problem for me because the workaround is easy, and I don't really need to render this server-side, but I spent time debugging, and SSR is default in Next.js, so I thought I'd at least post my findings.

Workaround:
Don't render on the server (I was able to wrap the component via [NoSSR](https://github.com/kadirahq/react-no-ssr/blob/af5d770590fd9bb3c7f776f76c48acda4f0f9797/src/index.js))

Reproduction steps:
* Use Next.js to render a pie
  * Can checkout my repo/commit https://github.com/keyserj/ameliorate/commit/598288f12ffca639b34545f0088c3de1e33b4a9f and run

```bash
cd web
npm i
npm run dev # open localhost:3000/pie and see the `Prop did not match` error in devtools console
```

* Notably, if you force a re-render on the client side (locally can just save a code change and Next.js will re-render without refreshing the page), interactivity works again

Info discovered from debugging:
* React hydration [doesn't reliably patch mismatches](https://reactjs.org/docs/react-dom.html#hydrate:~:text=React%20expects%20that,case%20of%20mismatches.) between server and client rendering
* Slice's id is a [function of the current time](https://github.com/psychobolt/react-pie-menu/blob/091431b21426527fbea007d5a1e92838334b31d2/src/PieMenu.container.js#L21)
* I believe these cause the problem because
  * component renders on server first with a time-based id
  * HTML is sent to client, client re-renders with new time-based id for hydration but does not patch the mismatch in ids
  * ids are relied on for JS interactivity (I assume), so the HTML still has the server-rendered ids but JS is using the client-rendered ones?

Solution ideas:
I'm not aware of the intent of using a time-based id, but if the main reason is to solve the list-key uniqueness [problem](https://reactjs.org/docs/lists-and-keys.html#keys), perhaps
* keying on index is good enough, since it doesn't seem like a common use case to re-order pie slices
* `Slice` could accept a key as a prop

**Comment by psychobolt** [comment]
Yes, `Slice` ids (`itemId`) are relied for capturing the active slice for touch devices. Interactively, touch users can hold to highlight and release to select a slice, since there is no hover event for touch devices capturing relies on pointer calculations. The captured `itemId` is then forwarded as a render state prop. I agree that using current time was not a great idea. Probably better to use the key from `PieMenu`. As long as a unique salt is passed as a prop from PieMenu, we could accept that as part of the id generation for each `Slice`.

**Comment by psychobolt** [comment]
Used React's built in hook [`useId`](https://github.com/psychobolt/react-pie-menu/blob/7ab53d705ad13461f473e275501ff12da7f1ede7/src/PieMenu.container.js#L35) as it [supports SSR](https://reactjs.org/docs/hooks-reference.html#useid). Please test out [1.0.0-alpha.3](https://www.npmjs.com/package/react-pie-menu/v/1.0.0-alpha.3)

**Comment by keyserj** [comment]
Oh nice find, TIL. Confirmed first render works on 1.0.0-alpha.3 🎉
